-- GTA V Base Game / Base
-- Location: Max Renda  (-585.8247, -282.72, 35.4547)

return {
    id = "gtav_base",
    label = "Base",
    category = "GTA V Base Game",
    coords = { x = -585.8247, y = -282.72, z = 35.4547 },
    interior_id = nil,
    ipls = {
        load = {
            "CS1_02_cf_onmission1",
            "CS1_02_cf_onmission2",
            "CS1_02_cf_onmission3",
            "CS1_02_cf_onmission4",
            "CanyonRvrShallow",
            "Carwash_with_spinners",
            "Coroner_Int_on",
            "FIBlobby",
            "FINBANK",
            "FruitBB",
            "atriumglmission",
            "bh1_47_joshhse_unburnt",
            "bh1_47_joshhse_unburnt_lod",
            "bkr_bi_hw1_13_int",
            "bkr_bi_id1_23_door",
            "canyonriver01",
            "canyonriver01_lod",
            "ch1_02_open",
            "coronertrash",
            "cs3_05_water_grp1",
            "cs3_05_water_grp1_lod",
            "cs5_4_trains",
            "des_farmhouse",
            "dockcrane1",
            "dt1_05_hc_remove",
            "dt1_17_newbill",
            "dt1_21_prop_lift_on",
            "facelobby",
            "farm",
            "farm_lod",
            "farm_props",
            "farmint",
            "ferris_finale_anim",
            "hei_sm_16_interior_v_bahama_milo_",
            "hw1_02_newbill",
            "hw1_emissive_newbill",
            "id2_14_during1",
            "id2_14_during_door",
            "ld_rail_01_track",
            "ld_rail_02_track",
            "lr_cs6_08_grave_closed",
            "methtrailer_grp1",
            "pcranecont",
            "post_hiest_unload",
            "refit_unload",
            "sc1_01_newbill",
            "sc1_14_newbill",
            "sp1_10_real_interior",
            "sp1_10_real_interior_lod",
            "trv1_trail_start",
            "v_tunnel_hole",
        },
        remove = {
            "dt1_05_hc_end",
            "dt1_05_hc_req",
        },
    },
    variants = {},
    defaults = {},
}