return {
    id = "factory",
    label = "Factory",
    category = "Agents of Sabotage",
    min_build = 3407,
    coords = { x = 752.31, y = -997.24, z = -47.0 },
    interior_id = 297729,
    ipls = {
        load = { "m24_2_garment_factory" },
        remove = {},
    },
    variants = {
        Trophy = {
            _type = "select",
            _nullable = false,
            options = {
                egg = "set_pent_rob_egg",
                idol01 = "set_pent_rob_idol_01",
                idol02 = "set_pent_rob_idol_02",
                scarab = "set_zanc_scarab",
                drive = "set_whistle_drive",
                plane = "set_cargo",
            },
        },
        Sonar = { _type = "toggle", options = { on = "set_sonar", off = "" } },
        Drive = { _type = "toggle", options = { on = "set_malware_drive", off = "" } },
        Controller = { _type = "toggle", options = { on = "set_rc_controller", off = "" } },
        Thermite = { _type = "toggle", options = { on = "set_thermal", off = "" } },
        Key = { _type = "toggle", options = { on = "set_smartkey", off = "" } },
        Drone = { _type = "toggle", options = { on = "set_pent_drone", off = "" } },
        Case = { _type = "toggle", options = { on = "set_pent_emp", off = "" } },
        Armor = { _type = "toggle", options = { on = "set_zanc_armor", off = "" } },
        Keycard = { _type = "toggle", options = { on = "set_zanc_keycard", off = "" } },
    },
    defaults = {},
}
