return {
    id = "arena",
    label = "Arena",
    category = "Arena War",
    min_build = 1604,
    coords = { x = 2800.0, y = -3800.0, z = 100.0 },
    interior_id = nil,
    ipls = {
        load = {
            "xs_arena_interior",
            "xs_arena_interior_mod",
            "xs_arena_interior_mod_2",
            "xs_arena_interior_vip",
            "xs_int_placement_xs",
            "xs_arena_banners_ipl",
        },
        remove = {},
    },
    variants = {
        Stage = {
            _type = "stages",
            _nullable = false,
            options = {
                dystopian_01  = { "Set_Dystopian_Scene", "Set_Dystopian_01"  },
                dystopian_02  = { "Set_Dystopian_Scene", "Set_Dystopian_02"  },
                dystopian_03  = { "Set_Dystopian_Scene", "Set_Dystopian_03"  },
                dystopian_04  = { "Set_Dystopian_Scene", "Set_Dystopian_04"  },
                dystopian_05  = { "Set_Dystopian_Scene", "Set_Dystopian_05"  },
                dystopian_06  = { "Set_Dystopian_Scene", "Set_Dystopian_06"  },
                dystopian_07  = { "Set_Dystopian_Scene", "Set_Dystopian_07"  },
                dystopian_08  = { "Set_Dystopian_Scene", "Set_Dystopian_08"  },
                dystopian_09  = { "Set_Dystopian_Scene", "Set_Dystopian_09"  },
                dystopian_10  = { "Set_Dystopian_Scene", "Set_Dystopian_10"  },
                dystopian_11  = { "Set_Dystopian_Scene", "Set_Dystopian_11"  },
                dystopian_12  = { "Set_Dystopian_Scene", "Set_Dystopian_12"  },
                dystopian_13  = { "Set_Dystopian_Scene", "Set_Dystopian_13"  },
                dystopian_14  = { "Set_Dystopian_Scene", "Set_Dystopian_14"  },
                dystopian_15  = { "Set_Dystopian_Scene", "Set_Dystopian_15"  },
                dystopian_16  = { "Set_Dystopian_Scene", "Set_Dystopian_16"  },
                dystopian_17  = { "Set_Dystopian_Scene", "Set_Dystopian_17"  },
                scifi_01      = { "Set_Scifi_Scene", "Set_Scifi_01" },
                scifi_02      = { "Set_Scifi_Scene", "Set_Scifi_02" },
                scifi_03      = { "Set_Scifi_Scene", "Set_Scifi_03" },
                scifi_04      = { "Set_Scifi_Scene", "Set_Scifi_04" },
                scifi_05      = { "Set_Scifi_Scene", "Set_Scifi_05" },
                scifi_06      = { "Set_Scifi_Scene", "Set_Scifi_06" },
                scifi_07      = { "Set_Scifi_Scene", "Set_Scifi_07" },
                scifi_08      = { "Set_Scifi_Scene", "Set_Scifi_08" },
                scifi_09      = { "Set_Scifi_Scene", "Set_Scifi_09" },
                scifi_10      = { "Set_Scifi_Scene", "Set_Scifi_10" },
                wasteland_01  = { "Set_Wasteland_Scene", "Set_Wasteland_01" },
                wasteland_02  = { "Set_Wasteland_Scene", "Set_Wasteland_02" },
                wasteland_03  = { "Set_Wasteland_Scene", "Set_Wasteland_03" },
                wasteland_04  = { "Set_Wasteland_Scene", "Set_Wasteland_04" },
                wasteland_05  = { "Set_Wasteland_Scene", "Set_Wasteland_05" },
                wasteland_06  = { "Set_Wasteland_Scene", "Set_Wasteland_06" },
                wasteland_07  = { "Set_Wasteland_Scene", "Set_Wasteland_07" },
                wasteland_08  = { "Set_Wasteland_Scene", "Set_Wasteland_08" },
                wasteland_09  = { "Set_Wasteland_Scene", "Set_Wasteland_09" },
                wasteland_10  = { "Set_Wasteland_Scene", "Set_Wasteland_10" },
            },
        },
        CrowdA = {
            _type = "toggle",
            _nullable = false,
            options = { on = "Set_Crowd_A", off = "" },
        },
        CrowdB = {
            _type = "toggle",
            _nullable = false,
            options = { on = "Set_Crowd_B", off = "" },
        },
        CrowdC = {
            _type = "toggle",
            _nullable = false,
            options = { on = "Set_Crowd_C", off = "" },
        },
        CrowdD = {
            _type = "toggle",
            _nullable = false,
            options = { on = "Set_Crowd_D", off = "" },
        },
    },
    defaults = {
        Stage = "dystopian_01",
        CrowdA = "on",
        CrowdB = "on",
        CrowdC = "on",
        CrowdD = "on",
    },
}
