return {
    id = "document_forgery",
    label = "Document Forgery",
    category = "Bikers",
    coords = { x = 1165.0, y = -3196.6, z = -39.0131 },
    interior_id = 246785,
    ipls = {
        load = { "bkr_biker_interior_placement_interior_6_biker_dlc_int_ware05_milo" },
        remove = {},
    },
    variants = {
        Style = {
            _type = "select",
            _nullable = false,
            options = { basic = "interior_basic", upgrade = "interior_upgrade" },
        },
        Equipment = {
            _type = "select",
            _nullable = false,
            options = { basic = "equipment_basic", upgrade = "equipment_upgrade" },
        },
        Security = {
            _type = "select",
            _nullable = false,
            options = { basic = "security_low", upgrade = "security_high" },
        },
        Production = { _type = "toggle", options = { on = "production", off = "" } },
        Furnitures = { _type = "toggle", options = { on = "set_up", off = "" } },
        Clutter = { _type = "toggle", options = { on = "clutter", off = "" } },
        Chair01 = { _type = "toggle", options = { on = "chair01", off = "" } },
        Chair02 = { _type = "toggle", options = { on = "chair02", off = "" } },
        Chair03 = { _type = "toggle", options = { on = "chair03", off = "" } },
        Chair04 = { _type = "toggle", options = { on = "chair04", off = "" } },
        Chair05 = { _type = "toggle", options = { on = "chair05", off = "" } },
        Chair06 = { _type = "toggle", options = { on = "chair06", off = "" } },
        Chair07 = { _type = "toggle", options = { on = "chair07", off = "" } },
    },
    defaults = {
        Style = "basic",
        Equipment = "basic",
        Security = "basic",
        Chair01 = "on",
        Chair02 = "on",
        Chair03 = "on",
        Chair04 = "on",
        Chair05 = "on",
        Chair06 = "on",
        Chair07 = "on",
    },
}
