-- The Contract / Office2 (Arcadius)

return {
    id = "security_office2",
    label = "Office2",
    category = "The Contract",
    min_build = 2545,
    coords = { x = -1040.46, y = -109.73, z = -95.3 },
    interior_id = nil,
    ipls = {
        load = {
            "sf_fixeroffice_hw1_08",
        },
        remove = {
        },
    },
    variants = {
        Entities = {
            _type = "select",
            _nullable = false,
            options = {
                Entity_Set_Armoury = "Entity_Set_Armoury",
                Entity_Set_Standard_Office = "Entity_Set_Standard_Office",
                Entity_Set_Blocker = "Entity_Set_Blocker",
                Entity_Set_Wpaper_1 = "Entity_Set_Wpaper_1",
                Entity_Set_Wpaper_3 = "Entity_Set_Wpaper_3",
                Entity_Set_Wpaper_2 = "Entity_Set_Wpaper_2",
                Entity_Set_Wpaper_4 = "Entity_Set_Wpaper_4",
                Entity_Set_Wpaper_5 = "Entity_Set_Wpaper_5",
                Entity_Set_Wpaper_6 = "Entity_Set_Wpaper_6",
                Entity_Set_Wpaper_7 = "Entity_Set_Wpaper_7",
                Entity_Set_Wpaper_8 = "Entity_Set_Wpaper_8",
                Entity_Set_Wpaper_9 = "Entity_Set_Wpaper_9",
                Entity_Set_Moving = "Entity_Set_Moving",
                Entity_Set_Tint_AG = "Entity_Set_Tint_AG",
                Entity_Set_Spare_Seats = "Entity_Set_Spare_Seats",
                Entity_Set_Player_Seats = "Entity_Set_Player_Seats",
                Entity_Set_Player_Desk = "Entity_Set_Player_Desk",
                Entity_Set_M_Golf_Intro = "Entity_Set_M_Golf_Intro",
                Entity_Set_M_Setup = "Entity_Set_M_Setup",
                Entity_Set_M_Nightclub = "Entity_Set_M_Nightclub",
                Entity_Set_M_Yacht = "Entity_Set_M_Yacht",
                Entity_Set_M_Promoter = "Entity_Set_M_Promoter",
                Entity_Set_M_Limo_Photo = "Entity_Set_M_Limo_Photo",
                Entity_Set_M_Limo_Wallet = "Entity_Set_M_Limo_Wallet",
                Entity_Set_M_The_Way = "Entity_Set_M_The_Way",
                Entity_Set_M_Billionaire = "Entity_Set_M_Billionaire",
                Entity_Set_M_Families = "Entity_Set_M_Families",
                Entity_Set_M_Ballas = "Entity_Set_M_Ballas",
                Entity_Set_M_Hood = "Entity_Set_M_Hood",
                Entity_Set_M_Fire_Booth = "Entity_Set_M_Fire_Booth",
                Entity_Set_M_50 = "Entity_Set_M_50",
                Entity_Set_M_Taxi = "Entity_Set_M_Taxi",
                Entity_Set_M_Gone_Golfing = "Entity_Set_M_Gone_Golfing",
                Entity_Set_M_Motel = "Entity_Set_M_Motel",
                Entity_Set_M_Construction = "Entity_Set_M_Construction",
                Entity_Set_M_Hit_List = "Entity_Set_M_Hit_List",
                Entity_Set_M_Tuner = "Entity_Set_M_Tuner",
                Entity_Set_M_Attack = "Entity_Set_M_Attack",
                Entity_Set_M_Vehicles = "Entity_Set_M_Vehicles",
                Entity_Set_M_Trip_01 = "Entity_Set_M_Trip_01",
                Entity_Set_M_Trip_02 = "Entity_Set_M_Trip_02",
                Entity_Set_M_Trip_03 = "Entity_Set_M_Trip_03",
                Entity_set_disc_01 = "Entity_set_disc_01",
                Entity_set_disc_02 = "Entity_set_disc_02",
                Entity_set_disc_03 = "Entity_set_disc_03",
                Entity_set_disc_04 = "Entity_set_disc_04",
                Entity_set_disc_05 = "Entity_set_disc_05",
                Entity_set_disc_06 = "Entity_set_disc_06",
                Entity_Set_Art_1 = "Entity_Set_Art_1",
                Entity_Set_Art_2 = "Entity_Set_Art_2",
                Entity_Set_Art_3 = "Entity_Set_Art_3",
            },
        },
},
    defaults = {},
    cull_models = {
        "hei_hw1_08_hotplaz01",
        "hw1_08_hotplaz_rail",
        "hw1_08_emissive_c",
    },
    cull_coords = nil, -- TODO: stand inside Office2 and run: ipls_cull_pos
}
