return {
    id = "hangar",
    label = "Hangar",
    category = "Smuggler's Run",
    coords = { x = -1267.0, y = -3013.135, z = -49.5 },
    interior_id = 260353,
    ipls = {
        load = {
            "sm_smugdlc_interior_placement_interior_0_smugdlc_int_01_milo_",
        },
        remove = {},
    },
    variants = {
        Floor = {
            _type = "select",
            _nullable = false,
            options = {
                raw = "set_floor_1",
                plain = "set_floor_2",
                decal1 = "set_floor_decal_1",
                decal2 = "set_floor_decal_2",
                decal4 = "set_floor_decal_3",
                decal3 = "set_floor_decal_4",
                decal5 = "set_floor_decal_5",
                decal6 = "set_floor_decal_6",
                decal7 = "set_floor_decal_7",
                decal8 = "set_floor_decal_8",
                decal9 = "set_floor_decal_9",
            },
        },
        Style = {
            _type = "select",
            _nullable = false,
            options = {
                raw = "set_floor_1",
                plain = "set_floor_2",
            },
        },
        Decals = {
            _type = "select",
            _nullable = false,
            options = {
                decal1 = "set_floor_decal_1",
                decal2 = "set_floor_decal_2",
                decal4 = "set_floor_decal_3",
                decal3 = "set_floor_decal_4",
                decal5 = "set_floor_decal_5",
                decal6 = "set_floor_decal_6",
                decal7 = "set_floor_decal_7",
                decal8 = "set_floor_decal_8",
                decal9 = "set_floor_decal_9",
            },
        },
        Office = {
            _type = "select",
            _nullable = false,
            options = {
                basic = "set_office_basic",
                modern = "set_office_modern",
                traditional = "set_office_traditional",
            },
        },
        Bedroom = {
            _type = "select",
            _nullable = false,
            options = {
                opened = "set_bedroom_blinds_open",
                closed = "set_bedroom_blinds_closed",
            },
        },
        Lighting = {
            _type = "select",
            _nullable = false,
            options = {
                yellow = "set_lighting_wall_tint09",
                blue = "set_lighting_wall_tint01",
                white = "set_lighting_wall_tint07",
                neutral = "set_lighting_wall_neutral",
                orange = "set_lighting_wall_tint02",
                lightYellow = "set_lighting_wall_tint03",
                lightYellow2 = "set_lighting_wall_tint04",
                dimmed = "set_lighting_wall_tint05",
                strongYellow = "set_lighting_wall_tint06",
                lightGreen = "set_lighting_wall_tint08",
            },
        },
        Ceiling = {
            _type = "select",
            _nullable = false,
            options = {
                yellow = "set_lighting_hangar_a",
                blue = "set_lighting_hangar_b",
                white = "set_lighting_hangar_c",
            },
        },
        Walls = {
            _type = "select",
            _nullable = false,
            options = {
                neutral = "set_lighting_wall_neutral",
                blue = "set_lighting_wall_tint01",
                orange = "set_lighting_wall_tint02",
                lightYellow = "set_lighting_wall_tint03",
                lightYellow2 = "set_lighting_wall_tint04",
                dimmed = "set_lighting_wall_tint05",
                strongYellow = "set_lighting_wall_tint06",
                white = "set_lighting_wall_tint07",
                lightGreen = "set_lighting_wall_tint08",
                yellow = "set_lighting_wall_tint09",
            },
        },
        Cranes = {
            _type = "toggle",
            _nullable = false,
            options = { on = "set_crane_tint", off = "" },
        },
        CranesColor = {
            _type = "color",
            _nullable = false,
            entity_set = "set_crane_tint",
            options = {
                colorSet1 = 1,
                colorSet2 = 2,
                colorSet3 = 3,
                colorSet4 = 4,
                colorSet5 = 5,
                colorSet6 = 6,
                colorSet7 = 7,
                colorSet8 = 8,
                colorSet9 = 9,
            },
        },
        ModArea = {
            _type = "toggle",
            _nullable = false,
            options = { on = "set_modarea", off = "" },
        },
        ModAreaColor = {
            _type = "color",
            _nullable = false,
            entity_set = "set_modarea",
            options = {
                colorSet1 = 1,
                colorSet2 = 2,
                colorSet3 = 3,
                colorSet4 = 4,
                colorSet5 = 5,
                colorSet6 = 6,
                colorSet7 = 7,
                colorSet8 = 8,
                colorSet9 = 9,
            },
        },
        BedroomStyle = {
            _type = "stages",
            _nullable = false,
            options = {
                none = "",
                modern = { "set_bedroom_modern", "set_bedroom_tint" },
                traditional = { "set_bedroom_traditional", "set_bedroom_tint" },
            },
        },
        BedroomClutter = {
            _type = "toggle",
            _nullable = false,
            options = { on = "set_bedroom_clutter", off = "" },
        },
        WallsColor = {
            _type = "color",
            _nullable = false,
            entity_set = "set_tint_shell",
            options = {
                colorSet1 = 1,
                colorSet2 = 2,
                colorSet3 = 3,
                colorSet4 = 4,
                colorSet5 = 5,
                colorSet6 = 6,
                colorSet7 = 7,
                colorSet8 = 8,
                colorSet9 = 9,
            },
        },
        FakeLights = {
            _type = "color",
            _nullable = false,
            entity_set = "set_lighting_tint_props",
            options = {
                white = 0,
                blue = 1,
                yellow = 2,
            },
        },
        DecalsColor = {
            _type = "color",
            _nullable = false,
            _target = "Decals",
            options = {
                colorSet1 = 1,
                colorSet2 = 2,
                colorSet3 = 3,
                colorSet4 = 4,
                colorSet5 = 5,
                colorSet6 = 6,
                colorSet7 = 7,
                colorSet8 = 8,
                colorSet9 = 9,
            },
        },
        BedroomStyleColor = {
            _type = "color",
            _nullable = false,
            entity_set = "set_bedroom_tint",
            options = {
                colorSet1 = 1,
                colorSet2 = 2,
                colorSet3 = 3,
                colorSet4 = 4,
                colorSet5 = 5,
                colorSet6 = 6,
                colorSet7 = 7,
                colorSet8 = 8,
                colorSet9 = 9,
            },
        },
    },
    defaults = {
        Style = "plain",
        Decals = "decal1",
        Office = "basic",
        Bedroom = "opened",
        Ceiling = "yellow",
        Walls = "neutral",
        CranesColor = "colorSet1",
        ModAreaColor = "colorSet1",
        WallsColor = "colorSet1",
        DecalsColor = "colorSet1",
        BedroomStyleColor = "colorSet1",
    },
}
